(() => {
  const DB_NAME = 'bennu-service-reports', DB_VERSION = 3;
  let client = null;
  const req = request => new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
  const clean = value => String(value || '').trim();
  const comparable = value => clean(value).toLocaleLowerCase('es');
  const open = () => new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains('pending-reports')) { const s = db.createObjectStore('pending-reports', { keyPath: 'id' }); s.createIndex('createdAt', 'createdAt'); }
      if (!db.objectStoreNames.contains('drafts')) db.createObjectStore('drafts', { keyPath: 'userId' });
      if (!db.objectStoreNames.contains('catalog_clients')) db.createObjectStore('catalog_clients', { keyPath: 'id' });
      if (!db.objectStoreNames.contains('catalog_equipment')) { const s = db.createObjectStore('catalog_equipment', { keyPath: 'id' }); s.createIndex('client_id', 'client_id'); s.createIndex('updated_at', 'updated_at'); }
      if (!db.objectStoreNames.contains('catalog_meta')) db.createObjectStore('catalog_meta', { keyPath: 'key' });
      if (!db.objectStoreNames.contains('pending_equipment')) db.createObjectStore('pending_equipment', { keyPath: 'local_id' });
    };
    request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error);
  });
  async function store(name, mode, fn) { const db = await open(); return new Promise((resolve, reject) => { const tx = db.transaction(name, mode), s = tx.objectStore(name); let value; try { value = fn(s); } catch (error) { db.close(); reject(error); return; } tx.oncomplete = () => { db.close(); resolve(value); }; tx.onerror = () => { db.close(); reject(tx.error); }; tx.onabort = tx.onerror; }); }
  const all = name => store(name, 'readonly', s => req(s.getAll()));
  const putMany = (name, rows) => store(name, 'readwrite', s => { for (const row of rows) s.put(row); });
  const meta = async key => (await store('catalog_meta', 'readonly', s => req(s.get(key))))?.value || null;
  const setMeta = (key, value) => store('catalog_meta', 'readwrite', s => s.put({ key, value }));
  async function page(table, lastSync) { let rows = [], from = 0; for (;;) { let q = client.from(table).select('*').order('updated_at').range(from, from + 499); if (lastSync) q = q.gt('updated_at', lastSync); const { data, error } = await q; if (error) throw error; rows.push(...(data || [])); if (!data || data.length < 500) break; from += 500; } return rows; }
  async function sync() { if (!client || !navigator.onLine) throw new Error('Sin conexiÃ³n'); const cmark = await meta('last_clients_sync'), emark = await meta('last_equipment_sync'), started = new Date().toISOString(); const clients = await page('clients', cmark), equipment = await page('equipment', emark); await putMany('catalog_clients', clients); await putMany('catalog_equipment', equipment); await setMeta('last_clients_sync', started); await setMeta('last_equipment_sync', started); await setMeta('last_catalog_sync', started); window.dispatchEvent(new CustomEvent('bennu:catalog-updated', { detail: { at: started } })); return { clients: clients.length, equipment: equipment.length, at: started }; }
  async function clients() { return (await all('catalog_clients')).filter(x => x.active).sort((a, b) => a.name.localeCompare(b.name, 'es')); }
  async function equipment(clientId) { return (await store('catalog_equipment', 'readonly', s => req(s.index('client_id').getAll(clientId)))).filter(x => x.active).sort((a, b) => [a.equipment_name, a.brand, a.model, a.serial_number].join('|').localeCompare([b.equipment_name, b.brand, b.model, b.serial_number].join('|'), 'es')); }
  async function findOrCreate(data) { if (!client || !navigator.onLine) throw new Error('Sin conexiÃ³n'); const client_id = data.clientId; if (!client_id) throw new Error('Cliente registrado requerido'); let q = client.from('equipment').select('*').eq('client_id', client_id); if (clean(data.serie)) q = q.eq('serial_number', clean(data.serie)); else if (clean(data.activo)) q = q.is('serial_number', null).eq('asset_number', clean(data.activo)); else q = q.is('serial_number', null).is('asset_number', null).eq('equipment_name', clean(data.equipo)).eq('brand', clean(data.marca)).eq('model', clean(data.modelo)); const { data: found, error } = await q.limit(1); if (error) throw error; if (found?.length) { await putMany('catalog_equipment', found); return found[0]; } const payload = { client_id, equipment_name: clean(data.equipo), brand: clean(data.marca) || null, model: clean(data.modelo) || null, serial_number: clean(data.serie) || null, asset_number: clean(data.activo) || null }; const { data: created, error: createError } = await client.from('equipment').insert(payload).select('*').single(); if (createError) throw createError; await putMany('catalog_equipment', [created]); return created; }
  async function queueEquipment(data) { const record = { local_id: data.pendingEquipmentLocalId || crypto.randomUUID(), created_at: new Date().toISOString(), data }; await store('pending_equipment', 'readwrite', s => s.put(record)); return record; }
  async function flushPending() { if (!navigator.onLine) return []; const pending = await all('pending_equipment'), done = []; for (const item of pending) { const created = await findOrCreate(item.data); await store('pending_equipment', 'readwrite', s => s.delete(item.local_id)); done.push({ local_id: item.local_id, equipment: created }); } return done; }
  async function validateEquipmentConflicts(clientId, equipmentId, changes) { const { data, error } = await client.from('equipment').select('id,equipment_name,brand,model,serial_number,asset_number').eq('client_id', clientId).neq('id', equipmentId); if (error) throw error; for (const item of data || []) { if (changes.serial_number && comparable(item.serial_number) === comparable(changes.serial_number)) return { field: 'Serie', item }; if (changes.asset_number && comparable(item.asset_number) === comparable(changes.asset_number)) return { field: 'Activo', item }; } return null; }
  async function updateExistingEquipment(request) { if (!client || !navigator.onLine) throw new Error('Sin conexiÃ³n'); const { equipmentId, clientId, changes } = request; const { data: current, error } = await client.from('equipment').select('*').eq('id', equipmentId).eq('client_id', clientId).single(); if (error) throw error; const payload = {}; for (const [key, value] of Object.entries(changes || {})) { const normalized = clean(value); if (normalized && normalized !== clean(current[key])) payload[key] = normalized; } if (!Object.keys(payload).length) return current; const conflict = await validateEquipmentConflicts(clientId, equipmentId, payload); if (conflict) { const e = new Error(`${conflict.field} ya estÃ¡ registrado en ${conflict.item.equipment_name} â€” ${conflict.item.brand || '-'} ${conflict.item.model || ''}`); e.code = 'EQUIPMENT_CONFLICT'; throw e; } const { data: updated, error: updateError } = await client.from('equipment').update(payload).eq('id', equipmentId).eq('client_id', clientId).select('*').single(); if (updateError) throw updateError; await putMany('catalog_equipment', [updated]); window.dispatchEvent(new CustomEvent('bennu:equipment-updated', { detail: updated })); return updated; }
  async function prepareReport(data) { if (data.saveEquipment && data.clientId && !data.equipmentId) { if (navigator.onLine) { const item = await findOrCreate(data); return { ...data, equipmentId: item.id, pendingEquipmentLocalId: null }; } const queued = await queueEquipment(data); return { ...data, equipmentId: null, pendingEquipmentLocalId: queued.local_id }; } if (data.pendingEquipmentLocalId && navigator.onLine) { const done = await flushPending(), match = done.find(x => x.local_id === data.pendingEquipmentLocalId); if (match) return { ...data, equipmentId: match.equipment.id, pendingEquipmentLocalId: null }; } return data; }
  function init(options) { client = options.supabase; }
  window.BennuCatalog = { init, sync, clients, equipment, lastSync: () => meta('last_catalog_sync'), findOrCreate, queueEquipment, flushPending, prepareReport, validateEquipmentConflicts, updateExistingEquipment };
})();
