(() => {
  const $=id=>document.getElementById(id);let db,allClients=[],allEquipment=[],ready=false;
  const option=(text,value)=>new Option(text,value);
  function build(){const clientInput=$('cliente'),clientWrap=clientInput.parentElement;clientWrap.insertAdjacentHTML('afterbegin','<label>Cliente registrado</label><select id="catalogClient"><option value="">Seleccione…</option><option value="manual">+ Cliente no registrado</option></select>');clientInput.placeholder='Nombre del cliente';clientInput.readOnly=true;const equipmentInput=$('equipo'),wrap=equipmentInput.parentElement;wrap.insertAdjacentHTML('afterbegin','<label>Equipo registrado</label><select id="catalogEquipment" disabled><option value="">Seleccione cliente primero</option></select><input id="catalogSearch" class="hidden" placeholder="Buscar equipo, marca, modelo, serie o activo">');wrap.insertAdjacentHTML('beforeend','<div class="btns"><button type="button" id="catalogManualEdit">Editar datos manualmente</button></div>');$('activo').parentElement.insertAdjacentHTML('beforeend','<label id="catalogSaveWrap" class="hidden"><input id="catalogSaveEquipment" type="checkbox" style="width:auto"> Guardar este equipo para futuras visitas</label>');const form=$('reporteForm');form.insertAdjacentHTML('afterbegin','<input type="hidden" id="catalogClientId"><input type="hidden" id="catalogEquipmentId"><div class="btns"><button type="button" id="catalogRefresh">Actualizar catálogo</button><span id="catalogStatus" class="muted">Catálogo no disponible sin conexión</span></div>');$('catalogClient').onchange=onClient;$('catalogEquipment').onchange=onEquipment;$('catalogSearch').oninput=debounce(renderEquipment,200);$('catalogManualEdit').onclick=()=>manualEquipment(false);$('catalogRefresh').onclick=refresh}
  const debounce=(fn,ms)=>{let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}};
  const equipmentFields=()=>[$('equipo'),$('marca'),$('modelo'),$('serie'),$('activo')];
  function setReadOnly(value){equipmentFields().forEach(x=>x.readOnly=value)}
  function clearEquipment(){ $('catalogEquipmentId').value='';$('catalogEquipment').value='';equipmentFields().forEach(x=>x.value='') }
  async function onClient(){const id=$('catalogClient').value;clearEquipment();if(id==='manual'||!id){$('catalogClientId').value='';$('cliente').readOnly=false;$('cliente').value=id==='manual'?'':$('cliente').value;$('catalogEquipment').disabled=true;manualEquipment(true);return}const client=allClients.find(x=>x.id===id);$('catalogClientId').value=id;$('cliente').value=client?.name||'';$('cliente').readOnly=true;allEquipment=await BennuCatalog.equipment(id);$('catalogEquipment').disabled=false;$('catalogSearch').classList.toggle('hidden',allEquipment.length<=100);renderEquipment()}
  function label(item){return `${item.equipment_name||'-'} — ${[item.brand,item.model].filter(Boolean).join(' ')||'-'} — Serie: ${item.serial_number||'-'} — Activo: ${item.asset_number||'-'}`}
  function renderEquipment(){const el=$('catalogEquipment'),current=el.value,term=($('catalogSearch').value||'').toLowerCase();el.innerHTML='';el.add(option('+ Equipo no registrado','manual'));for(const item of allEquipment.filter(x=>!term||label(x).toLowerCase().includes(term)).slice(0,50))el.add(option(label(item),item.id));if([...el.options].some(x=>x.value===current))el.value=current}
  function onEquipment(){const id=$('catalogEquipment').value;if(id==='manual'){clearEquipment();manualEquipment(true);return}const item=allEquipment.find(x=>x.id===id);if(!item)return;$('catalogEquipmentId').value=id;$('equipo').value=item.equipment_name||'';$('marca').value=item.brand||'';$('modelo').value=item.model||'';$('serie').value=item.serial_number||'';$('activo').value=item.asset_number||'';setReadOnly(true);$('catalogSaveWrap').classList.add('hidden')}
  function manualEquipment(showSave){$('catalogEquipmentId').value='';setReadOnly(false);$('catalogSaveWrap').classList.toggle('hidden',!showSave||!$('catalogClientId').value)}
  async function loadLocal(){allClients=await BennuCatalog.clients();const el=$('catalogClient'),current=el.value;el.innerHTML='';el.add(option('Seleccione…',''));for(const item of allClients)el.add(option(item.name,item.id));el.add(option('+ Cliente no registrado','manual'));if([...el.options].some(x=>x.value===current))el.value=current}
  function formatDate(value){return value?new Date(value).toLocaleString('es-CR'):'Catálogo no disponible sin conexión'}
  async function refresh(){try{const result=await BennuCatalog.sync();await loadLocal();$('catalogStatus').textContent='Catálogo actualizado: '+formatDate(result.at)}catch(_){$('catalogStatus').textContent='No se pudo actualizar; se mantiene la copia local'}}
  async function init(options){if(ready)return;ready=true;db=options.supabase;BennuCatalog.init({supabase:db});build();await loadLocal();$('catalogStatus').textContent='Catálogo actualizado: '+formatDate(await BennuCatalog.lastSync());if(navigator.onLine)refresh();window.addEventListener('online',()=>BennuCatalog.flushPending().then(refresh).catch(()=>{}))}
  function capture(){return{clientId:$('catalogClientId')?.value||null,equipmentId:$('catalogEquipmentId')?.value||null,clientMode:$('catalogClient')?.value==='manual'?'manual':'registered',equipmentMode:$('catalogEquipment')?.value==='manual'?'manual':'registered',saveEquipment:!!$('catalogSaveEquipment')?.checked,pendingEquipmentLocalId:null}}
  async function restore(data){if(!ready)return;await loadLocal();if(data?.clientId&&allClients.some(x=>x.id===data.clientId)){$('catalogClient').value=data.clientId;await onClient();if(data.equipmentId&&allEquipment.some(x=>x.id===data.equipmentId)){$('catalogEquipment').value=data.equipmentId;onEquipment()}else manualEquipment(false)}else{$('catalogClient').value='manual';await onClient();$('cliente').value=data?.cliente||$('cliente').value}if($('catalogSaveEquipment'))$('catalogSaveEquipment').checked=!!data?.saveEquipment}
  window.BennuCatalogUI={init,capture,restore,prepare:data=>BennuCatalog.prepareReport(data)};
})();